name: sticky_header_footer
description: sticky header footer

version: 0.1.4

author: XIAOHENG LIU <xiaoheng.liu@gmail.com>
homepage: https://github.com/xhengx/sticky_header_footer


environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

